config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'guests#index'
  resources :guests do
      put :to_export, on: :member
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
        #  :registerable,
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :email, :password])
    end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  before_action :authenticate_user!

  def index
    @guests = Guest.all.order(:created_at)
    @guests_to_export = Guest.where("to_export = true")
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)
    @guest.save
    redirect_to guests_path
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def update
    @guest = Guest.find(params[:id])
    if @guest.update(guest_params)
      redirect_to guests_path
    else
      render :edit
    end
  end

  def destroy
    Guest.destroy(params[:id])
    redirect_to guests_path
  end

  def export
    redirect_to guests_path
    @guests = Guest.all.order(:created_at)
  end

  def to_export
    @guest = Guest.find(params[:id])
    @guest.toggle(:to_export).save
    @guests = Guest.all.order(:created_at)
    @guests_to_export = Guest.where("to_export = true")
  end

  private

  def guest_params
    params.require(:guest).permit(:name, :age, :heard, :purpose, :church, :description, :hostconnected, :whereseated, :actionplan, :to_export)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_exportbutton.html.erb
<!-- 1. Define some markup -->
<button class="btn btn-secondary m-2" data-clipboard-text="
<% guests_to_export.each do |guest| %>
Name & brief description: <%= guest.name %>
Age/Phase of life: <%= guest.age %>
How they heard about us: <%= guest.heard %>
Purpose of visit: <%= guest.purpose %>
Church/Ministry/Level of commitment: <%= guest.church %>
Seat: <%= guest.whereseated %>
Physical appearance description: <%= guest.description %>
Host(s) Connected: <%= guest.hostconnected %>
Action Plan: <%= guest.actionplan %>

<% end %>">
  Export to Telegram
</button>

<!-- 3. Instantiate clipboard by passing a string selector -->
<script>
  var clipboard = new Clipboard('.btn');
  clipboard.on('success', function(e) {
      console.log(e);
  });
  clipboard.on('error', function(e) {
      console.log(e);
  });
</script>

<a href="#top" class="btn btn-primary m-2">Back to top</a>

app/views/guests/_to_export.html.erb
<% guests.each do |guest| %>
<div class="card p-1 m-y-1">

  <p id="<%=guest.name.split(' ').join%>"><b>Name & brief description:</b> <%= guest.name %></p>
  <p><b>Age/Phase of life:</b> <%= guest.age %></p>
  <p><b>How they heard about us:</b> <%= guest.heard %></p>
  <p><b>Purpose of visit:</b> <%= guest.purpose %></p>
  <p><b>Church/Ministry/Level of commitment:</b> <%= guest.church %></p>
  <p><b>Seat:</b> <%= guest.whereseated %></p>
  <p><b>Physical appearance description:</b> <%= guest.description %></p>
  <p><b>Host(s) Connected:</b> <%= guest.hostconnected %></p>
  <p><b>Action Plan:</b> <%= guest.actionplan %></p>
  <p><%= link_to 'Edit', edit_guest_path(guest), class: "btn btn-secondary my-button" %></p>
  <p><%= link_to 'Delete', guest_path(guest), method: :delete, class: "btn btn-outline-danger my-button", data: {confirm: "Are you sure?"} %></p>
  <p>
    <%= link_to "#{ guest.to_export ? 'Remove from export' : 'Add to export'}", to_export_guest_path(guest), method: :put, class: "btn #{ guest.to_export ? 'btn-danger' : 'btn-success' }", remote: true %>
  </p>

</div>
<% end %>

app/views/guests/edit.html.erb
<div class="jumbotron">
  <h1>Editing guest details</h1>
</div>

<div class="container">
  <div class="col-10">
    <%= simple_form_for(@guest, html: { class: 'form-horizontal' }) do |f| %>
    <%= f.input :name, label: 'Name & brief description', placeholder: 'Mark and Lisa from Indonesia GBI' %>
    <%= f.input :age, label: 'Age/Phase of life', placeholder: 'Both are in early 40s' %>
    <%= f.input :heard, label: 'How they heard about us', placeholder: 'through Instagram' %>
    <%= f.input :purpose, label: 'Purpose of Visit', placeholder: 'both of them are Indonesians, visiting for the first time today. Lisa is here to attend her friend’s wedding and Husband Mark accompanies her. Decided to come check out HOGC while they are here. Flying back Jarkarta tomorrow.' %>
    <%= f.input :church, label: 'Church/Ministry/Level of commitment', placeholder: 'From Indonesia GBI church, Mark plays guitar for worship team, Lisa plays keyboard for worship team.' %>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary m-2" data-toggle="modal" data-target="#exampleModal">
      View Seating Plan
    </button>

    <!-- Modal -->
    <div class="modal fade modal-size" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Seating Plan</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= image_tag ("ImaginariumSeats.jpeg"), class: "img-fluid img-height" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <%= f.input :whereseated, label: 'Seat', placeholder: 'B2 third row, first from K2' %>
    <%= f.input :description, label: 'Physical appearance description', placeholder: 'Mark is in blue polo and dark jeans' %>
    <%= f.input :hostconnected, label: 'Host(s) Connected', placeholder: 'Kenneth' %>


      <%= f.input :to_export, inline_label: 'To export to Telegram?' %>
      <%= f.input :actionplan, label: 'Action Plan' %>
      <%= f.button :submit, class: "btn btn-success m-2" %>
    <% end %>
    <br>
    <%= link_to 'Delete', guest_path(@guest.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger m-2" %>
    <%= link_to 'Back to home', guests_path, class: "btn btn-primary m-2" %>
  </div>
</div>

app/views/guests/export.html.erb
<%= link_to 'Back to home', guests_path, class: "btn btn-primary" %>

app/views/guests/index.html.erb
<h3 class="jumbotron fluid">Host Guest Tracker</h3><br>
<div class="container-fluid" id = "top">
  <div class="col-12">

    <%= link_to 'Add new guest', new_guest_path, class: "btn btn-info" %>
    <br><br>

    <div class="card p-1">
      <h5>Guests</h5>
      <% @guests.each.with_index do |guest, index| %>
      <p><b><%= index + 1 %>. <a href= #<%= guest.name.split(' ').join %> > <%= guest.name %> </a></b></p>
      <% end %>
    </div>


    <div id="to-export">
      <%= render partial: 'to_export', locals: { guests: @guests } %>
    </div>


    <br>

    <div id="exportbutton">
      <%= render partial: 'exportbutton', locals: { guests_to_export: @guests_to_export } %>
    </div>

  </div>
</div>


<br>

app/views/guests/new.html.erb
<div class="jumbotron">
  <h1>Please enter guest details</h1>
</div>

<div class="container">
  <div class="col-10">
    <%= simple_form_for(@guest, html: { class: 'form-horizontal' }) do |f| %>
      <%= f.input :name, label: 'Name & brief description', placeholder: 'Mark and Lisa from Indonesia GBI' %>
      <%= f.input :age, label: 'Age/Phase of life', placeholder: 'Both are in early 40s' %>
      <%= f.input :heard, label: 'How they heard about us', placeholder: 'through Instagram' %>
      <%= f.input :purpose, label: 'Purpose of Visit', placeholder: 'both of them are Indonesians, visiting for the first time today. Lisa is here to attend her friend’s wedding and Husband Mark accompanies her. Decided to come check out HOGC while they are here. Flying back Jarkarta tomorrow.' %>
      <%= f.input :church, label: 'Church/Ministry/Level of commitment', placeholder: 'From Indonesia GBI church, Mark plays guitar for worship team, Lisa plays keyboard for worship team.' %>

      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary m-2" data-toggle="modal" data-target="#exampleModal">
        View Seating Plan
      </button>

      <!-- Modal -->
      <div class="modal fade modal-size" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Seating Plan</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= image_tag ("ImaginariumSeats.jpeg"), class: "img-fluid img-height" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      <%= f.input :whereseated, label: 'Seat', placeholder: 'B2 third row, first from K2' %>
      <%= f.input :description, label: 'Physical appearance description', placeholder: 'Mark is in blue polo and dark jeans' %>
      <%= f.input :hostconnected, label: 'Host(s) Connected', placeholder: 'Kenneth' %>
      <%= f.button :submit, class: "btn btn-success m-2" %>
    <% end %>
    <%= link_to 'Back to home', guests_path, class: "btn btn-primary m-2" %>
  </div>

</div>

app/views/guests/old_index.html.erb
<div class="container-fluid">
  <div class="col-12">

    <h3>Host Guest Tracker</h3><br>

    <table class="my_table">
      <thead class="thead-inverse">
        <tr>
          <th>Guest Name(s)</th>
          <th>Guest Age(s)</th>
          <th>Description</th>
          <th>Host(s) Connected</th>
          <th>Guest(s) seated at</th>
          <th>Leader/Pastor?</th>
          <th>To be connected?</th>
          <th colspan="3">Action Plan</th>
        </tr>
      </thead>
      <tbody>
        <% @guests.each do |guest| %>
        <tr>
          <td><%= guest.name %></td>
          <td><%= guest.age %></td>
          <td><%= guest.description %></td>
          <td><%= guest.hostconnected %></td>
          <td><%= guest.whereseated %></td>
          <td><%= guest.leaderorpastor %></td>
          <td><%= guest.tobeconnected %></td>
          <td><%= guest.actionplan %></td>
          <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
          <td><%= link_to 'Delete', guest_path(guest), method: :delete %></td>
        </tr>
        <% end %>
      </tbody>

    </table>
    <br>
    <%= link_to 'Add new guest', new_guest_path, class: "btn btn-info" %>
    <!-- 1. Define some markup -->
    <button class="btn" data-clipboard-text="
    <% @guests.each do |guest| %>
Guest Name(s): <%= guest.name %>
Guest Age(s): <%= guest.age %>
Description: <%= guest.description %>
Host(s) Connected: <%= guest.hostconnected %>
Guest(s) seated at: <%= guest.whereseated %>
Leader/Pastor?: <%= guest.leaderorpastor %>
To be connected?: <%= guest.tobeconnected %>
Action Plan: <%= guest.actionplan %>

<% end %>">Export to Telegram</button>

    <!-- 2. Include library -->
    <script src="../dist/clipboard.min.js"></script>

    <!-- 3. Instantiate clipboard by passing a string selector -->
    <script>
    var clipboard = new Clipboard('.btn');
    clipboard.on('success', function(e) {
        console.log(e);
    });
    clipboard.on('error', function(e) {
        console.log(e);
    });
    </script>
  </div>
</div>

app/views/guests/to_export.js.erb
$("#to-export").html("<%= j render partial: 'to_export', locals: { guests: @guests} %>");
$("#exportbutton").html("<%= j render partial: 'exportbutton', locals: { guests_to_export: @guests_to_export} %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Host Guest Tracker</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/clipboard@1/dist/clipboard.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
       <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </body>
</html>